---
title: "Matching sensor overlap"
author: "Jose Eduardo Meireles"
output:
  rmarkdown::pdf_document:
vignette: > 
  %\VignetteIndexEntry{How to match the sensor overlaps}
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library("spectrolab")
knitr::opts_chunk$set(echo = TRUE)
```

# The problem

Spectra may have overlap regions between two sensors and the reflectance or radiance values can have abrupt 'jumps' in those regions. In those cases, the regions between sensors need to be matched (spliced).

Unspliced spectra collected with a 3-sensor instrument (e.g. an SVC) may look like this:

```{r, fig.height=6, fig.width=4, fig.align='center', echo=TRUE}

# Path to raw (unmatched) spectra
path_raw = system.file("extdata/svc_raw_and_overlap_matched_serbin/SVC_Files", 
                       package = "spectrolab") 

# Read spectra as reflectance and radiance
reflect_raw  = read_spectra(path   = path_raw,
                            format = "SIG",
                            type   = "target_reflectance")

radiance_raw = read_spectra(path   = path_raw,
                            format = "SIG",
                            type   = "target_radiance")


# Sensor overlaps marked with vertical dashed lines
par(mfrow = c(2, 1))

plot(reflect_raw, main = "Reflectance", lwd = 0.5, cex.main = 0.7, cex.lab = 0.7, cex.axis = 0.7)
abline(v = c(990, 1900), col = "red", lty = 2, lwd = 0.5)

plot(radiance_raw, main = "Radiance", lwd = 0.5, cex.main = 0.7, cex.lab = 0.7, cex.axis =0.7)
abline(v = c(990, 1900), col = "red", lty = 2, lwd = 0.5)
```

# The solution

```{r, fig.height=6, fig.width=4, fig.align='center', echo=TRUE}

splice_bands = c(990, 1900)

reflect_matched = match_sensors(x               = reflect_raw,
                                splice_at       = splice_bands,
                                interpolate_wvl = c(5, 1))

radiance_matched = match_sensors(x               = radiance_raw,
                                 splice_at       = splice_bands,
                                 interpolate_wvl = c(5, 1))

lwd = 0.5
cex = 0.7
par(mfrow = c(2, 1))


plot(reflect_raw, main = "Reflectance",
     lwd = lwd, cex.main = cex, cex.lab = cex, cex.axis = cex)

plot(reflect_matched, col = "red", add = TRUE,
     lwd = lwd, cex.main = cex, cex.lab = cex, cex.axis = cex)


plot(radiance_raw, main = "Radiance",
     lwd = lwd, cex.main = cex, cex.lab = cex, cex.axis = cex)

plot(radiance_matched, col = "red", add = TRUE,
     lwd = lwd, cex.main = cex, cex.lab = cex, cex.axis = cex)
```




